### ISSUE TITLE
Fix message displaying on the console

### ISSUE THREAD

**Issue by Sepehrworklife** [Sepehrworklife/doc-viewer-cli#2]
Hello guys,
https://github.com/Sepehrworklife/doc-viewer-cli/blob/a201bc58cc7e5f798954b92651bbec5bd44c70bc/src/utils.py#L22-L23
need help updating the error message in the above section.
It's a good issue for starting, if anybody wants to do it let me know please so I assign this issue to him/her.
hint: `run: python application ....`

Thanks in advance.

**Comment by Sepehrworklife** [comment]
Make sure to read [CONTRIBUTING.md](https://github.com/Sepehrworklife/doc-viewer-cli/blob/master/COUNTRIBUTING.md) before any cooperating

**Comment by Sepehrworklife** [comment]
assigned to @sarinaodr,

**Comment by Sepehrworklife** [comment]
@sarinaodr Please say something here, so i can assign it to you.

**Comment by sarinaodr** [comment]
Well I'm here to do that, but I'm totally lost 
is that normal?! :D

**Comment by Sepehrworklife** [comment]
> Well I'm here to do that, but I'm totally lost is that normal?! :D

Yes, it is normal :smile:
first, try to run the project as CONTRIBUTING.md said.
then you will have some clues to fix that.
feel free to ask any questions.

**Comment by Sepehrworklife** [comment]
Hello @sarinaodr.
I wanted to know about your progress, if you have any questions I will be happy to answer them.
There is no pressure from timing for this issue, just want to check.

**Comment by sarinaodr** [comment]
Hello @Sepehrworklife 
well, I try to understand how the application works and learn it 😅
but about the error message, I don't know exactly what should I do 🙄
I think I have to see you to understand what's going on in this project 😁

**Comment by sarinaodr** [comment]
Hello dear @Sepehrworklife 
I've done this issue, I think 🤔, but making new branch is not available for me 😅
I want to ask you where should I push my code on the master branch?

**Comment by Sepehrworklife** [comment]
Greetings @sarinaodr 
Firstly you must fork the repository, then you can create a new branch.
Please follow contribute document at the root of the project for more details.

**Comment by Sepehrworklife** [comment]
This issue has been resolved.
The pull request has been accepted and waiting to merge: #8 
This issue was closed due to completion.

Thanks for all the efforts.
